CREATE TYPE appt_status AS ENUM ('active', 'cancelled', 'completed');

CREATE TABLE IF NOT EXISTS working_days (
  work_date date UNIQUE NOT NULL,
  slots text[] NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS appointments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_tg_id bigint NOT NULL,
  client_name text NOT NULL,
  work_date date NOT NULL,
  time_slot text NOT NULL,
  status appt_status DEFAULT 'active'::appt_status,
  created_at timestamp with time zone DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_active_appointment ON appointments (work_date, time_slot) WHERE status = 'active';

CREATE OR REPLACE FUNCTION get_working_days_in_month(p_year int, p_month int) RETURNS TABLE (working_date date) AS $$
BEGIN RETURN QUERY SELECT work_date FROM working_days WHERE EXTRACT(YEAR FROM work_date) = p_year AND EXTRACT(MONTH FROM work_date) = p_month AND array_length(slots, 1) > 0; END; $$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION get_free_slots(p_date date) RETURNS TABLE (available_time text) AS $$
BEGIN RETURN QUERY SELECT unnest(slots) FROM working_days WHERE work_date = p_date EXCEPT SELECT time_slot FROM appointments WHERE work_date = p_date AND status = 'active' ORDER BY 1; END; $$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION book_appointment(p_tg_id bigint, p_name text, p_date date, p_time text) RETURNS boolean AS $$
BEGIN INSERT INTO appointments (client_tg_id, client_name, work_date, time_slot, status) VALUES (p_tg_id, p_name, p_date, p_time, 'active'); RETURN true; EXCEPTION WHEN unique_violation THEN RETURN false; END; $$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION set_working_day(p_date date, p_slots text[]) RETURNS void AS $$
BEGIN INSERT INTO working_days (work_date, slots) VALUES (p_date, p_slots) ON CONFLICT (work_date) DO UPDATE SET slots = EXCLUDED.slots; END; $$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION get_appointments_by_date(p_date date) RETURNS TABLE (time_slot text, client_name text, status appt_status) AS $$
BEGIN RETURN QUERY SELECT a.time_slot, a.client_name, a.status FROM appointments a WHERE a.work_date = p_date AND a.status = 'active' ORDER BY a.time_slot; END; $$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION delete_working_day(p_date date) RETURNS void AS $$
BEGIN DELETE FROM working_days WHERE work_date = p_date; END; $$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION get_day_slots(p_date date) RETURNS text[] AS $$
DECLARE result text[]; BEGIN SELECT slots INTO result FROM working_days WHERE work_date = p_date; RETURN result; END; $$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION remove_time_slot(p_date date, p_time text) RETURNS void AS $$
BEGIN UPDATE working_days SET slots = array_remove(slots, p_time) WHERE work_date = p_date; END; $$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION get_client_appointments(p_tg_id bigint) 
RETURNS TABLE (appointment_id bigint, work_date date, time_slot text) AS $$
BEGIN
  RETURN QUERY 
  SELECT id, a.work_date, a.time_slot 
  FROM appointments a 
  WHERE client_tg_id = p_tg_id AND status = 'active' 
  ORDER BY a.work_date ASC, a.time_slot ASC;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION cancel_appointment_by_client(p_appointment_id bigint, p_tg_id bigint) 
RETURNS boolean AS $$
DECLARE
  v_updated_id bigint;
BEGIN
  UPDATE appointments 
  SET status = 'cancelled' 
  WHERE id = p_appointment_id 
    AND client_tg_id = p_tg_id 
    AND status = 'active'
  RETURNING id INTO v_updated_id;
  
  RETURN v_updated_id IS NOT NULL;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION cancel_appointment_by_admin(p_appointment_id bigint) 
RETURNS void AS $$
BEGIN
  UPDATE appointments 
  SET status = 'cancelled' 
  WHERE id = p_appointment_id;
END;
$$ LANGUAGE plpgsql;

ALTER TABLE working_days ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on working_days" 
ON working_days 
FOR SELECT
USING (true);