CREATE TABLE IF NOT EXISTS services (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  duration_minutes int DEFAULT 60, 
  price numeric DEFAULT 0,         
  is_active boolean DEFAULT true,  
  created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE appointments 
  ADD COLUMN IF NOT EXISTS service_id bigint REFERENCES services(id),
  ADD COLUMN IF NOT EXISTS client_username text,
  ADD COLUMN IF NOT EXISTS client_phone text;


CREATE OR REPLACE FUNCTION add_service(p_name text, p_duration int, p_price numeric) 
RETURNS bigint AS $$
DECLARE
  v_id bigint;
BEGIN
  INSERT INTO services (name, duration_minutes, price)
  VALUES (p_name, p_duration, p_price)
  RETURNING id INTO v_id;
  RETURN v_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_service(p_id bigint, p_name text, p_duration int, p_price numeric, p_is_active boolean) 
RETURNS void AS $$
BEGIN
  UPDATE services
  SET name = p_name, 
      duration_minutes = p_duration, 
      price = p_price, 
      is_active = p_is_active
  WHERE id = p_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION get_services(p_only_active boolean DEFAULT false) 
RETURNS TABLE (id bigint, name text, duration_minutes int, price numeric, is_active boolean) AS $$
BEGIN
  IF p_only_active THEN
    RETURN QUERY SELECT s.id, s.name, s.duration_minutes, s.price, s.is_active FROM services s WHERE s.is_active = true ORDER BY s.id;
  ELSE
    RETURN QUERY SELECT s.id, s.name, s.duration_minutes, s.price, s.is_active FROM services s ORDER BY s.id;
  END IF;
END;
$$ LANGUAGE plpgsql;

DROP FUNCTION IF EXISTS get_appointments_by_date(date);
CREATE OR REPLACE FUNCTION get_appointments_by_date(p_date date) 
RETURNS TABLE (
  id bigint, 
  time_slot text, 
  client_name text, 
  client_username text,
  client_phone text,
  service_name text,
  status appt_status
) AS $$
BEGIN 
  RETURN QUERY 
  SELECT 
    a.id, 
    a.time_slot, 
    a.client_name, 
    a.client_username,
    a.client_phone,
    s.name AS service_name,
    a.status 
  FROM appointments a 
  LEFT JOIN services s ON a.service_id = s.id
  WHERE a.work_date = p_date AND a.status = 'active' 
  ORDER BY a.time_slot; 
END; 
$$ LANGUAGE plpgsql;

DROP FUNCTION IF EXISTS book_appointment(bigint, text, date, text);
CREATE OR REPLACE FUNCTION book_appointment(
  p_tg_id bigint, 
  p_name text, 
  p_username text,
  p_phone text,
  p_date date, 
  p_time text,
  p_service_id bigint
) RETURNS boolean AS $$
BEGIN 
  INSERT INTO appointments (client_tg_id, client_name, client_username, client_phone, work_date, time_slot, service_id, status) 
  VALUES (p_tg_id, p_name, p_username, p_phone, p_date, p_time, p_service_id, 'active'); 
  RETURN true; 
EXCEPTION WHEN unique_violation THEN 
  RETURN false; 
END; 
$$ LANGUAGE plpgsql;



ALTER TABLE services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access on services" ON services FOR SELECT USING (true);

INSERT INTO services (name, duration_minutes, price) 
VALUES 
  ('💅 Маникюр с покрытием гель-лак', 120, 2500),
  ('✨ Наращивание ногтей', 180, 4000),
  ('👣 Педикюр (полный)', 90, 3000)
ON CONFLICT DO NOTHING;